#!/bin/bash

# MedJourney 对话存储服务手动部署脚本
# 服务器信息：
# IP: 36.50.226.131
# 密码: 10mZSt1mpYBDKt5
# IPv6: 2408:8653:dc00:20b:500::4

set -e

echo "🚀 MedJourney 对话存储服务手动部署指南"
echo "=========================================="

# 服务器配置
SERVER_IP="36.50.226.131"
SERVER_USER="root"
SERVER_PASSWORD="10mZSt1mpYBDKt5"
SERVICE_PORT="8000"
REMOTE_PROJECT_PATH="/opt/medjourney/conversation-storage-service"

echo "📋 部署步骤："
echo ""
echo "1️⃣ 连接到服务器："
echo "   ssh $SERVER_USER@$SERVER_IP"
echo "   密码: $SERVER_PASSWORD"
echo ""
echo "2️⃣ 在服务器上执行以下命令："
echo ""
echo "   # 创建项目目录"
echo "   mkdir -p $REMOTE_PROJECT_PATH"
echo ""
echo "   # 安装Docker（如果未安装）"
echo "   curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
echo ""
echo "   # 安装Docker Compose（如果未安装）"
echo "   curl -L \"https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
echo ""
echo "3️⃣ 将项目文件上传到服务器："
echo ""
echo "   方法1: 使用scp（需要输入密码）"
echo "   scp -r ./* $SERVER_USER@$SERVER_IP:$REMOTE_PROJECT_PATH/"
echo ""
echo "   方法2: 使用rsync（如果已安装）"
echo "   rsync -avz --progress ./ $SERVER_USER@$SERVER_IP:$REMOTE_PROJECT_PATH/"
echo ""
echo "4️⃣ 在服务器上启动服务："
echo ""
echo "   cd $REMOTE_PROJECT_PATH"
echo "   docker-compose up -d --build"
echo ""
echo "5️⃣ 检查服务状态："
echo ""
echo "   docker-compose ps"
echo "   docker-compose logs -f"
echo ""
echo "6️⃣ 测试API："
echo ""
echo "   curl http://$SERVER_IP:$SERVICE_PORT/api/v1/health"
echo ""
echo "📊 服务信息："
echo "   🌐 API地址: http://$SERVER_IP:$SERVICE_PORT"
echo "   📖 API文档: http://$SERVER_IP:$SERVICE_PORT/docs"
echo "   🔍 健康检查: http://$SERVER_IP:$SERVICE_PORT/api/v1/health"
echo ""
echo "🔧 常用管理命令："
echo "   # 查看服务状态"
echo "   docker-compose ps"
echo ""
echo "   # 查看日志"
echo "   docker-compose logs -f"
echo ""
echo "   # 重启服务"
echo "   docker-compose restart"
echo ""
echo "   # 停止服务"
echo "   docker-compose down"
echo ""
echo "   # 更新服务"
echo "   docker-compose pull && docker-compose up -d --build"
echo ""
echo "📝 注意事项："
echo "   - 确保服务器防火墙开放端口 $SERVICE_PORT"
echo "   - 数据库文件存储在 ./data/ 目录中"
echo "   - 服务会自动重启（unless-stopped）"
echo "   - 日志会实时输出到控制台"
echo ""
echo "✅ 部署完成后，TEN Agent 可以通过以下地址访问："
echo "   http://$SERVER_IP:$SERVICE_PORT"
echo ""
echo "🎉 部署指南完成！" 